security:
    encoders:
        App\Entity\Customer:
            algorithm: auto
        App\Entity\UserBack:
            algorithm: auto

    providers:
        customer:
            entity:
                class: App\Entity\Customer
                property: email
        userBack:
            entity:
                class: App\Entity\UserBack
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        customer:
            provider: customer
            pattern: ^/customer
            
            # error  a fix
            custom_authenticators:
                - App\Security\CustomerAuthenticator

        userBack:
            provider: userBack
            pattern: ^/jurassicback
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserBackAuthenticator
 
        main:
            pattern: ^/
            anonymous: true
            logout:
                path: security.logout
    
    access_control:
        # customer
        #- { path: ^/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/customer, roles: ROLE_CUSTOMER}
        # userBack
        - { path: ^/jurassicback/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/jurassicback, roles: ROLE_USERBACK}